name: Update dev sheet
on:
  schedule:
    - cron: "0 * * * *"  # Run once an hour
jobs:
  update-dev-sheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure git user
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"

      - name: Download dev spreadsheet from Google Sheets
        run: |
          wget --no-check-certificate --output-document=dev_sheet.xlsx "https://docs.google.com/spreadsheets/d/${{ secrets.DEV_SHEET_ID }}/export?format=xlsx"
          
      - name: Commit and push dev spreadsheet
        run: |
          git add dev_sheet.xlsx
          git commit -m "Update dev sheet"
          git push origin main
